version: "3.9"
services:
  web:
    build: ../..
    environment:
      DATABASE_URL: mongodb://database/app
    networks:
      - graphql-server
    depends_on:
      - "database"
  database:
    image: mongo
    networks:
      - graphql-server

networks:
  graphql-server:
