name: Build and Test
on: [push]

jobs:
  lint:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: ["16.x", "lts/fermium"]
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
          cache-dependency-path: "node_modules/.cache/mongodb-memory-server/mongodb-binaries"

      - run: npm ci
      - run: npm run lint

  format:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: ["16.x", "lts/fermium"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm run format:check

  build:
    needs: [lint, format]
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        node: ["16.x", "lts/fermium"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm run build

  test:
    needs: [lint, format]
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node: ["16.x", "lts/fermium"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm test
